name: ${DOCKER_NAME:-huly}
services:
  nginx:
    image: "nginx:1.21.3"
    ports:
      - "${HTTP_BIND}:${HTTP_PORT}:80"
    volumes:
      - ./.huly.nginx:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  cockroach:
    image: cockroachdb/cockroach:latest-v24.2
    command: start-single-node --accept-sql-without-tls
    environment:
      - COCKROACH_DATABASE=${CR_DATABASE}
      - COCKROACH_USER=${CR_USERNAME}
      - COCKROACH_PASSWORD=${CR_USER_PASSWORD}
    volumes:
      - ${VOLUME_CR_DATA_PATH:-cr_data}:/cockroach/cockroach-data
      - ${VOLUME_CR_CERTS_PATH:-cr_certs}:/cockroach/certs
    restart: unless-stopped

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.6
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --default-log-level=info
    volumes:
      - ${VOLUME_REDPANDA_PATH:-redpanda}:/var/lib/redpanda/data
    environment:
      - REDPANDA_SUPERUSER_USERNAME=${REDPANDA_ADMIN_USER}
      - REDPANDA_SUPERUSER_PASSWORD=${REDPANDA_ADMIN_PWD}
    healthcheck:
      test:
        [
          "CMD",
          "rpk",
          "cluster",
          "info",
          "-X",
          "user=${REDPANDA_ADMIN_USER}",
          "-X",
          "pass=${REDPANDA_ADMIN_PWD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ${VOLUME_FILES_PATH:-files}:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      retries: 10
    restart: unless-stopped

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - ${VOLUME_ELASTIC_PATH:-elastic}:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped

  rekoni:
    image: ${IMAGE_REKONI:-hardcoreeng/rekoni-service:${HULY_VERSION}}
    environment:
      - SECRET=${SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped

  transactor:
    image: ${IMAGE_TRANSACTOR:-hardcoreeng/transactor:${HULY_VERSION}}
    depends_on:
      redpanda:
        condition: service_healthy
      account:
        condition: service_started
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http${SECURE:+s}://${HOST_ADDRESS}
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - AI_BOT_URL=${AI_BOT_URL:-}
      - QUEUE_CONFIG=redpanda:9092
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "const n=require('net');const p=process.env.SERVER_PORT||3333;const s=n.connect({host:'127.0.0.1',port:p});s.setTimeout(2000);s.on('connect',()=>{s.destroy();process.exit(0)});s.on('error',()=>process.exit(1));s.on('timeout',()=>process.exit(1));"
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped

  collaborator:
    image: ${IMAGE_COLLABORATOR:-hardcoreeng/collaborator:${HULY_VERSION}}
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped

  account:
    image: ${IMAGE_ACCOUNT:-hardcoreeng/account:${HULY_VERSION}}
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws${SECURE:+s}://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http${SECURE:+s}://${HOST_ADDRESS}
      - STATS_URL=http://stats:4900
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http${SECURE:+s}://${HOST_ADDRESS}
      - ACCOUNT_PORT=3000
      - QUEUE_CONFIG=redpanda:9092
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          node -e "const n=require('net');const p=process.env.SERVER_PORT||3000;const s=n.connect({host:'127.0.0.1',port:p});s.setTimeout(2000);s.on('connect',()=>{s.destroy();process.exit(0)});s.on('error',()=>process.exit(1));s.on('timeout',()=>process.exit(1));"
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  workspace:
    image: ${IMAGE_WORKSPACE:-hardcoreeng/workspace:${HULY_VERSION}}
    depends_on:
      redpanda:
        condition: service_healthy
      account:
        condition: service_started
      transactor:
        condition: service_healthy
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws${SECURE:+s}://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - FULLTEXT_URL=http://fulltext:4700
      - QUEUE_CONFIG=redpanda:9092
      - ACCOUNTS_DB_URL=${CR_DB_URL}
    restart: unless-stopped

  front:
    image: ${IMAGE_FRONT:-hardcoreeng/front:${HULY_VERSION}}
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${SECRET}
      - LOVE_ENDPOINT=http${SECURE:+s}://${HOST_ADDRESS}/_love
      - ACCOUNTS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_accounts
      - ACCOUNTS_URL_INTERNAL=http://account:3000
      - REKONI_URL=http${SECURE:+s}://${HOST_ADDRESS}/_rekoni
      - CALENDAR_URL=http${SECURE:+s}://${HOST_ADDRESS}/_calendar
      - GMAIL_URL=http${SECURE:+s}://${HOST_ADDRESS}/_gmail
      - TELEGRAM_URL=http${SECURE:+s}://${HOST_ADDRESS}/_telegram
      - STATS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws${SECURE:+s}://${HOST_ADDRESS}/_collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - TITLE=${TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - DESKTOP_UPDATES_CHANNEL=${HULY_VERSION}
      - AI_URL=${AI_URL:-}
    restart: unless-stopped

  fulltext:
    image: ${IMAGE_FULLTEXT:-hardcoreeng/fulltext:${HULY_VERSION}}
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - FULLTEXT_DB_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped

  stats:
    image: ${IMAGE_STATS:-hardcoreeng/stats:${HULY_VERSION}}
    depends_on:
      account:
        condition: service_started
    environment:
      - PORT=4900
      - SERVER_SECRET=${SECRET}
    restart: unless-stopped

  # Optional: Love (audio/video calls via LiveKit)
  love:
    image: ${IMAGE_LOVE:-hardcoreeng/love:${HULY_VERSION}}
    profiles:
      - love
    ports:
      - 8096:8096
    environment:
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=${CR_DB_URL}
      - STORAGE_PROVIDER_NAME=minio
      - PORT=8096
      - LIVEKIT_HOST=${LIVEKIT_HOST:-}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY:-}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET:-}
    restart: unless-stopped

  # Optional: AI Bot
  aibot:
    image: ${IMAGE_AIBOT:-hardcoreeng/ai-bot:${HULY_VERSION}}
    profiles:
      - aibot
    ports:
      - 4010:4010
    environment:
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - SERVER_SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=${CR_DB_URL}
      - STATS_URL=http://stats:4900
      - FIRST_NAME=${AI_BOT_FIRST_NAME:-Bot}
      - LAST_NAME=${AI_BOT_LAST_NAME:-Huly AI}
      - PASSWORD=${AI_BOT_PASSWORD:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-}
      - LOVE_ENDPOINT=http://love:8096
    restart: unless-stopped
volumes:
  # These named volumes are used when custom volume paths are not specified
  # If VOLUME_*_PATH variables are set, these volumes will be ignored
  elastic:
  files:
  cr_data:
  cr_certs:
  redpanda:
